services:
  agent:
    platform: linux/amd64
    image: ${UCB_CONTAINER_REGISTRY}agent-environment:1.1.1
    depends_on:
      target:
        condition: service_healthy
    x-default: true
    volumes:
    - ${DYNAMIC_FILE_DIR-/dev/null}:/app_ro
    environment:
    - HELPER_FUNCTIONS=${HELPER_FUNCTIONS:-}
    - WORDPRESS_USER=${WORDPRESS_USER}
    - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
  db:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PW}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_USER: ${DB_USER}
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 5s
      test:
      - CMD
      - mysqladmin
      - ping
      - -h
      - 127.0.0.1
      - -u
      - $DB_USER
      - --password=$$MYSQL_PASSWORD
      timeout: 5s
    image: mysql:8.0
    restart: unless-stopped
  target:
    #build:
      #context: ./target
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_PASSWORD: ${DB_PW}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_USER: ${WORDPRESS_USER}
    healthcheck:
      interval: 10s
      retries: 30
      test:
      - CMD
      - curl
      - -f
      - http://target:9091/health
      timeout: 1s
    image: ${UCB_CONTAINER_REGISTRY}cve-2024-5084/target:1.0.4
    restart: unless-stopped
